### ISSUE TITLE
Complier needed?

### ISSUE THREAD

**Issue by TRusselo** [matitalatina/torque-hass-proxy#1]
Just to clearify, your instructions say to compile and run on android with termux?

from what i can tell termux is not a compiler.  so we need to compile first?

Maybe edit to:  ....compile, (comma) then run on android using termux....

2nd  what compiler?  from googling, its pointing to google code compiler? correct?
is this all really necessary?     can i just copy/paste raw code to new file, then run file in termux?  Or can you provide link to precompiled code in install.md?
Am I overthinking things?

**Comment by TRusselo** [comment]
or just make instructions idiot proof for people like me

**Comment by TRusselo** [comment]
1 month, no response.

**Comment by eddiman** [comment]
- Open up Termux, write `pkg install go`
- Wait until it finished, doublecheck by writing "go version" and see if a "go version go*.**.* android/arm64" shows up.

To easily get the files to your device without copying files from SD or USb or whatever:
- Still in Termux, write `pkg install git`
- Wait until git is installed
- Write `git clone https://github.com/martitalatina/torque-hass-proxy`
- When cloning is done, write `cd torque-hass-proxy`, (should be a tab-symbol right next to "ESC"-btn for autocomplete.
- Inside the "torque-hass-proxy"-folder you can now build the GO-file. Write `go build main.go`
- If you type in an `ls` command you will now see a "main.go" and "main"-file without a file extension, this is the file you're gonna run.

From here on, just follow the README, just switch out `./termux-proxy ....` with `./main ....`

**Comment by matitalatina** [comment]
I improved the README with the [Getting Started](https://github.com/matitalatina/torque-hass-proxy#getting-started) section.

Now you don't need the compilation anymore. I created [a release](https://github.com/matitalatina/torque-hass-proxy/releases/tag/v1.0.0) with some executables already compiled.
I hope is clearer now.

Sorry for the late reply. Better late than never 😄
